export const PAGE_TITLES = {
  dashboardOverview: "Dashboard Overview",
  dietaryBaselineAnalysis: "Dietary Baseline Analysis",
  behaviorChangeAnalysis: "Behavior Change Analysis",
  socialInfluenceAnalysis: "Social Influence Analysis",
  wasteTrackingAnalysis: "Waste Tracking Analysis",
  mealLog: {
    nutritionAnalytics: "Nutrition Analytics",
    foodPopularity: "Food Popularity",
    mealPatterns: "Meal Patterns",
    sustainability: "Sustainability",
    mealClassification: "Meal Classification",
    demographicInsights: "Demographic Insights",
  },
  shoppingList: {
    itemPopularity: "Item Popularity",
    listPatterns: "List Patterns",
    nutritionProfile: "Nutrition Profile",
    sustainability: "Sustainability",
    demographicInsights: "Demographic Insights",
    crossDimensionalAnalysis: "Cross-dimensional Analysis",
  },
  recipes: {
    overview: "Recipe Overview & Popularity",
    dietLifestyle: "Diet & Lifestyle",
    nutrition: "Nutrition Insights",
    sustainability: "Sustainability",
    ingredients: "Ingredient Analytics",
    trendsPatterns: "Trends & Patterns",
  },
} as const;
